<x-layout>
	<x-product-filter-bar
		:categories="$categories"
		:sort-options="$sort_options"
		:selected-categories="$selected_categories"
		:selected-categoryIds="$selected_category_ids"
		:highest-price="$highest_price"
		:lowest-price="$lowest_price"
		:selected-price="$selected_price"
		:selected-sort-option-id="$selected_sort_option_id"
	/>
</x-layout>